version: 2.1.{build}
branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10.20.1 x64
  - npm i

build_script:
  - npm run build

test: off

artifacts:
  - path: 'build\*.exe'
  
environment:
  GH_TOKEN:
    secure: y97smtAJHffiwIV4gltGn41s6WuSmnZduTVckx00MFeROP1eM6r5ycn01YfjFXrg

deploy:
  - provider: GitHub
    auth_token:
      secure: y97smtAJHffiwIV4gltGn41s6WuSmnZduTVckx00MFeROP1eM6r5ycn01YfjFXrg
    artifact: build\*.exe
    draft: true
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true
