version: 2.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10.20.1 x64
  - choco install yarn --ignore-dependencies
  - git reset --hard HEAD
  - node --version
  - npm i

build_script:
  - npm run build

test: off

environment:
  GH_TOKEN:
    secure: y97smtAJHffiwIV4gltGn41s6WuSmnZduTVckx00MFeROP1eM6r5ycn01YfjFXrg
